import requests
from pact import Pact, Verifier, match

PROVIDER_URL = "http://localhost:8081"


def _write_consumer_contract(directory):
    """Build the Pact a mobile client would have published to a Pact Broker.

    In a real pipeline this contract is generated by the consumer's own test
    suite (see drill 01) and fetched from the Broker here. It's built inline
    so this drill can verify a real provider without a Broker running.
    """
    pact = Pact("MobileCheckoutApp", "OrdersService")
    (
        pact.upon_receiving("a request for the current orders")
        .given("orders exist")
        .with_request("GET", "/api/pact/orders")
        .will_respond_with(200)
        .with_body(
            {
                "orders": match.each_like(
                    {
                        "id": match.like("ORD-101"),
                        "total": match.like(149.0),
                        "status": match.regex(
                            "COMPLETED", regex=r"COMPLETED|PENDING|CANCELLED"
                        ),
                        "currency": "USD",
                    }
                )
            }
        )
    )
    with pact.serve() as mock_server:
        requests.get(f"{mock_server.url}/api/pact/orders")
    pact.write_file(directory, overwrite=True)
    return directory / "MobileCheckoutApp-OrdersService.json"


def test_provider_honors_contract(tmp_path):
    pact_file = _write_consumer_contract(tmp_path)

    # Provider verification: replay the recorded contract against the real,
    # running OrdersService and let Pact decide whether it still holds --
    # not a hand-picked set of field checks.
    verifier = (
        Verifier("OrdersService").add_transport(url=PROVIDER_URL).add_source(pact_file)
    )
    verifier.verify()

    assert verifier.results["result"] is True
